title: "Portfólio Perícia Digital"
description: "Especialista em documentoscopia digital e análise forense"
baseurl: ""
url: "https://pericia.cvcyber.dev"

# Comment out theme for now - didn't work
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge
