title: "Portfólio Perícia Digital"
description: "Portfólio profissional especializado em perícia digital, autenticidade de documentos e análise forense."
author: Carla Vieira
email: carla@cvcyber.dev

url: "https://pericia.cvcyber.dev"
baseurl: ""

markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

collections:
  casos:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "casos"
    values:
      layout: "caso"

safe: true
incremental: false

professional:
  name: Carla Vieira
  title: "Perito em Forense Digital"
  contact:
    phone: "+55 (61) 991688071"
    linkedin: "https://www.linkedin.com/in/carlacovieira"
    location: Brasília, DF

social:
  name: Carla Vieira
  type: "Person"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
