# Site settings
title: "Portfólio Perícia Digital"
description: "Perito especializado em documentoscopia digital e análise forense"
url: "https://pericia.cvcyber.dev"
baseurl: ""

# Build settings
markdown: kramdown

# Collections for cases
collections:
  casos:
    output: true

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock